### ISSUE TITLE
timing

### ISSUE THREAD

**Issue by davidfof13** [HPCE/hpce_2014_cw5#12]
Is there a more reliable method of measuring time other than using the unix time command? Do you suggest creating our own timing infrastructure?

**Comment by m8pple** [comment]
Developing your own timing infrastructure is not a bad idea, as you want to directly
target the metric if possible. One approach is to use two tiny programs which copy
input to output - one prints the time when it sends the first byte of output, the other when it
receives the last byte of input.

Take note of the lessons from CW2 though, and make sure that IO does not become
a bottleneck (i.e. don't send individual bytes), and also the lessons from CW1, where
timer resolution needs to be taken into account when measuring short periods.
Also: make sure the two processes will definitely be reporting time from
the [same clock](http://linux.die.net/man/3/clock_gettime).
