### ISSUE TITLE
Testing Criteria and Makefile

### ISSUE THREAD

**Issue by tp1811** [HPCE/hpce_2014_cw5#13]
In the "Execution and Compilation" section you say that our program will be tested on a number of machines including a g2.2xlarge instance type for performance.  Can we assume that all the machines our program will be tested on will have an nvidia graphics card and will be running linux?

**Comment by m8pple** [comment]
You can assume that all machines will be running linux (unbuntu, #9) due
to the bootstrap script, but you shouldn't assume they will have nvidia GPUs.

Your code should be correct on any machine that is capable of running it (doing width=2^24
and levels=64 won't work on a micro instance), but only needs to be performant
on the GPU instance.

Cagey, I know, but part of the exercise is the decisions you make in the face
of limited information.
