### ISSUE TITLE
Correctness

### ISSUE THREAD

**Issue by kronocharia** [HPCE/hpce_2014_cw5#5]
In the correctness section

"The output images should be bit-accurate correct. Any conflict between the operation of this program and the definition of the image processing and image format should be seen as a bug in this program. For example, this program cannot handle very large images, which is a bug."

What is this referring to, imagemagick or process? Are you saying that process currently has a bug in that it cant handle very large images which we must address?

Also is it safe to assume if the binary outputs from our version of process and the original match, it is correct for that example input?

From our perspective, handling a single frame, and a series of frames, would they be the same? We are just taking an input stream of data and creating a processed output stream right? So we dont need to repackage them into frames of information and testing with a series of different single images should be good enough?

**Comment by m8pple** [comment]
"This program" refers to process.cpp (although imagemagick probably can't as well). If you try
putting a massive (but legal) width and height, then cat in /dev/null, you'd expect to see an
out of memory crash.

> Also is it safe to assume if the binary outputs from our version of process and the
> original match, it is correct for that example input?

Yes, that is correct. From an external observers point of view, the only meaningful
definition of correctness can be a binary diff. Though you'd probably want to check
on a plurality of inputs (boundary conditions, all white, all black, etc.)

Regarding multiple frames: you can test on single images, as long as you are confident that
the frame loop will still correctly move onto the next image. There is a danger associated
with that though, as experience suggests that people forget to free stuff - if I put 1000000 frames
through your system, are you sure there is no memory or context leak?

(You are also missing quite a big opportunity for parallelism if you only do one frame at
a time).
