### ISSUE TITLE
Extension of Deadline

### ISSUE THREAD

**Issue by skong125** [HPCE/hpce_2014_cw5#7]
I have spoken with David Thomas, and he is willing to extend the deadline by 3 days (Friday) given that some of us have quite a packed week next week. But he can only do this if people are happy with an extension. So please leave a comment if you want or don't want an extension, thanks :). 

*edit*
I think the response is a disturbingly positive. 
The following posts contain scenes of a very meme-ful nature.
Scroll down at your own risk.

**Comment by yuchen-w** [comment]
![image](http://gifsec.com/wp-content/uploads/2014/03/yes-gif.gif)

**Comment by iassael** [comment]
+1 :)

**Comment by JHFarrant** [comment]
Yes.

**Comment by davidfof13** [comment]
Fantastic

**Comment by Wasderr** [comment]
+1

**Comment by schmethan** [comment]
![image](http://replygif.net/i/159.gif)

**Comment by chungcyk** [comment]
![image](http://i1187.photobucket.com/albums/z393/KristineChavezRodriguez/yes1.gif)

**Comment by salmanarif** [comment]
![image](http://giant.gfycat.com/PointedAdmirableGangesdolphin.gif)

**Comment by martluide** [comment]
![image](https://cloud.githubusercontent.com/assets/3430280/6416188/1f6a3514-be9c-11e4-82a2-fc96314f3cc0.png)

**Comment by martluide** [comment]
![image](https://lh6.googleusercontent.com/-7gWKlUbcDao/TxBjCkCTN0I/AAAAAAAAAZA/RjIpjutxTq0/w371/yes%2Bno.gif)

**Comment by kronocharia** [comment]
![deey8kp](https://cloud.githubusercontent.com/assets/3238456/6416207/5750966c-be9c-11e4-8dfb-380573c7c911.gif)

Yesssss

**Comment by salmanarif** [comment]
![image](http://i.imgur.com/XwmEdGL.gif)

**Comment by yuchen-w** [comment]
Oh dear. What have I started...

![image](http://stream1.gifsoup.com/view1/20140114/4952691/what-have-i-done-o.gif)

**Comment by schmethan** [comment]
![image](http://media.tumblr.com/tumblr_m4xmeb6Ei41qj3ir1.gif)

**Comment by kronocharia** [comment]
Just enjoy the ride
![5c22rvf](https://cloud.githubusercontent.com/assets/3238456/6416358/78ed064c-be9d-11e4-8f3e-afca9083e4a3.gif)

**Comment by reginalio** [comment]
![11005599_10155218104850587_1332438931_n](https://cloud.githubusercontent.com/assets/6588346/6416356/779b98c6-be9d-11e4-8516-5166d08ded9f.jpg)

Mike loves it

**Comment by kronocharia** [comment]
She made it.... but....
![babhfpo](https://cloud.githubusercontent.com/assets/3238456/6416371/9571a016-be9d-11e4-90fc-1c1bdf0ae171.gif)

**Comment by kronocharia** [comment]
David Thomas as he checks github later...

![dt scary smile](https://cloud.githubusercontent.com/assets/3238456/6417362/d77d3680-bea4-11e4-90bf-61815bb18139.jpg)
"Ahhh I bet noone objected against the extension..."

![dt derp eyes](https://cloud.githubusercontent.com/assets/3238456/6417367/e65881e6-bea4-11e4-9603-3bcc076a696a.jpg)
"LOL good one guys"

![dt wtf](https://cloud.githubusercontent.com/assets/3238456/6417381/fcbfc7be-bea4-11e4-90c9-0233b86d8bd3.jpg)
"Oh wtf is that..?! o0"

![dt scary smile amused](https://cloud.githubusercontent.com/assets/3238456/6417396/1638206a-bea5-11e4-8cb1-621346a7eaea.jpg)
Ok then, this was a productive use of my evening

**Comment by tp1811** [comment]
yes please

**Comment by schmethan** [comment]
C-C-C-C-COMBO BREAKER

**Comment by m8pple** [comment]
![](http://cdn2.crushable.com/wp-content/uploads/2014/07/Kim-Kardashian-looking-at-Kanye-West-shaking-their-heads-GIF.gif)
